# Generated by Django 2.1.4 on 2018-12-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearablearmorslot',
            name='wearable_armor_slot',
            field=models.CharField(blank=True, choices=[('Charm', 'Charm'), ('Ears', 'Ears'), ('Head', 'Head'), ('Face', 'Face'), ('Neck', 'Neck'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Back', 'Back'), ('Wrists', 'Wrists'), ('Range', 'Range'), ('Hands', 'Hands'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Fingers', 'Fingers'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Feet', 'Feet'), ('Waist', 'Waist'), ('Ammo', 'Ammo'), ('Powersource', 'Powersource')], default=None, max_length=15),
        ),
    ]
