# Generated by Django 2.1.4 on 2020-06-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiparmorslot',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='equiparmorslot',
            name='aug1',
        ),
        migrations.RemoveField(
            model_name='equiparmorslot',
            name='aug2',
        ),
        migrations.RemoveField(
            model_name='equiparmorslot',
            name='character',
        ),
        migrations.RemoveField(
            model_name='equipaugmentation1',
            name='aug',
        ),
        migrations.RemoveField(
            model_name='equipaugmentation2',
            name='aug',
        ),
        migrations.DeleteModel(
            name='EquipArmorSlot',
        ),
        migrations.DeleteModel(
            name='EquipAugmentation1',
        ),
        migrations.DeleteModel(
            name='EquipAugmentation2',
        ),
    ]
