# Generated by Django 2.1.4 on 2020-06-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('armor', '0002_auto_20200601_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipArmorSlot',
            fields=[
                ('equip_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_equip_slot', models.CharField(choices=[('slot0', 'Charm'), ('slot1', 'LeftEar'), ('slot2', 'Head'), ('slot3', 'Face'), ('slot4', 'RightEar'), ('slot5', 'Neck'), ('slot6', 'Shoulder'), ('slot7', 'Arms'), ('slot8', 'Back'), ('slot9', 'LeftWrist'), ('slot10', 'RightWrist'), ('slot11', 'Range'), ('slot12', 'Hands'), ('slot13', 'Primary'), ('slot14', 'Secondary'), ('slot15', 'LeftFinger'), ('slot16', 'RightFinger'), ('slot17', 'Chest'), ('slot18', 'Legs'), ('slot19', 'Feet'), ('slot20', 'Waist'), ('slot21', 'Ammo'), ('slot22', 'PowerSource')], default=None, max_length=6, null=True)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.Armor')),
            ],
        ),
        migrations.CreateModel(
            name='EquipAugmentation1',
            fields=[
                ('equip_aug_slot1', models.AutoField(primary_key=True, serialize=False)),
                ('aug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.Augmentation')),
            ],
        ),
        migrations.CreateModel(
            name='EquipAugmentation2',
            fields=[
                ('equip_aug_slot2', models.AutoField(primary_key=True, serialize=False)),
                ('aug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.Augmentation')),
            ],
        ),
        migrations.AddField(
            model_name='equiparmorslot',
            name='aug1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.EquipAugmentation1'),
        ),
        migrations.AddField(
            model_name='equiparmorslot',
            name='aug2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.EquipAugmentation2'),
        ),
        migrations.AddField(
            model_name='equiparmorslot',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
    ]
