# Generated by Django 2.1.4 on 2022-03-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0003_auto_20200601_2049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armor',
            table='Armor',
        ),
        migrations.AlterModelTable(
            name='augmentation',
            table='Augmentation',
        ),
        migrations.AlterModelTable(
            name='equiparmorslot',
            table='Equip_Armor_Slot',
        ),
        migrations.AlterModelTable(
            name='equipaugmentation1',
            table='Equip_Augmentation_Slot1',
        ),
        migrations.AlterModelTable(
            name='equipaugmentation2',
            table='Equip_Augmentation_Slot2',
        ),
        migrations.AlterModelTable(
            name='wearablearmorslot',
            table='Wearable_Armor_Slot',
        ),
    ]
