# Generated by Django 2.1.4 on 2018-12-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('char_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_class', models.CharField(choices=[('WAR', 'Warrior'), ('CLR', 'Cleric'), ('PAL', 'Paladin'), ('RNG', 'Ranger'), ('SHD', 'Shadow Knight'), ('DRU', 'Druid'), ('BRD', 'Bard'), ('ROG', 'Rogue'), ('SHM', 'Shaman'), ('NEC', 'Necromancer'), ('WIZ', 'Wizard'), ('MAG', 'Magician'), ('ENC', 'Enchanter'), ('BST', 'Beastlord'), ('BER', 'Berserker'), ('MNK', 'Monk')], max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
