# Generated by Django 2.1.4 on 2022-03-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('epic_tracker', '0009_auto_20220322_1918'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='epicStatus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='epic_tracker.EpicStatus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
