# Generated by Django 2.1.4 on 2022-03-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20220322_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='epicStatus',
        ),
    ]
