# Generated by Django 2.1.4 on 2020-06-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='War_Epic_1_5_PreQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 1.5 Complete?')),
                ('epic_1_5_prequest_step1', models.BooleanField(default=False, verbose_name="Kill Diaku Overseer and loot Korbuk's weapon plans")),
                ('epic_1_5_prequest_step2', models.BooleanField(default=False, verbose_name='Hello World')),
                ('epic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
