# Generated by Django 2.1.4 on 2020-06-11 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war_epic_1_5_prequest',
            name='epic',
            field=models.OneToOneField(limit_choices_to={'char_class': 'WAR'}, on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AlterField(
            model_name='war_epic_1_5_prequest',
            name='epic_complete',
            field=models.BooleanField(),
        ),
    ]
