# Generated by Django 2.1.4 on 2022-03-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_tracker', '0002_auto_20220323_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wiz_Epic_1_5_PreQuest_Steps',
        ),
        migrations.AlterModelTable(
            name='epicstatus',
            table='Epic_Status',
        ),
    ]
