# Generated by Django 2.1.4 on 2020-06-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_tracker', '0003_auto_20200611_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war_epic_1_5_prequest',
            name='epic_complete',
            field=models.BooleanField(default=False, verbose_name='Epic 1.5 Complete?'),
        ),
    ]
