# Generated by Django 2.1.4 on 2020-06-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('epic_tracker', '0004_auto_20200611_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='War_epic_1_5_Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 1.5 Complete')),
                ('character_epic', models.OneToOneField(limit_choices_to={'char_class': 'WAR'}, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='War_epic_2_0_Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 2.0 Complete')),
                ('character_epic', models.OneToOneField(limit_choices_to={'char_class': 'WAR'}, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='war_epic_1_5_prequest',
            old_name='epic',
            new_name='character_epic',
        ),
        migrations.AlterField(
            model_name='war_epic_1_5_prequest',
            name='epic_complete',
            field=models.BooleanField(default=False, verbose_name='Epic 1.5 Pre Quest Complete'),
        ),
    ]
