# Generated by Django 2.1.4 on 2020-06-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('epic_tracker', '0005_auto_20200611_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='War_epic_1_5_Epic',
            new_name='War_epic_1_5',
        ),
        migrations.RenameModel(
            old_name='War_epic_2_0_Epic',
            new_name='War_epic_2_0',
        ),
    ]
