# Generated by Django 2.1.4 on 2020-06-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('epic_tracker', '0006_auto_20200611_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='War_1_5_Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 1.5 Quest Complete')),
                ('character_epic', models.OneToOneField(limit_choices_to={'char_class': 'WAR'}, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='War_2_0_Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 2.0 Quest Complete')),
                ('character_epic', models.OneToOneField(limit_choices_to={'char_class': 'WAR'}, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='War_Epic_1_5_PreQuest',
            new_name='War_1_5_Epic_PreQuest',
        ),
        migrations.RemoveField(
            model_name='war_epic_1_5',
            name='character_epic',
        ),
        migrations.RemoveField(
            model_name='war_epic_2_0',
            name='character_epic',
        ),
        migrations.DeleteModel(
            name='War_epic_1_5',
        ),
        migrations.DeleteModel(
            name='War_epic_2_0',
        ),
    ]
