# Generated by Django 2.1.4 on 2020-06-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('epic_tracker', '0007_auto_20200612_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='War_Epic_1_5_PreQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_complete', models.BooleanField(default=False, verbose_name='Epic 1.5 Complete?')),
                ('epic_1_5_prequest_step1', models.BooleanField(default=False, verbose_name="Kill Diaku Overseer and loot Korbuk's weapon plans")),
                ('epic_1_5_prequest_step2', models.BooleanField(default=False, verbose_name='Hello World')),
                ('epic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='war_1_5_epic',
            name='character_epic',
        ),
        migrations.RemoveField(
            model_name='war_1_5_epic_prequest',
            name='character_epic',
        ),
        migrations.RemoveField(
            model_name='war_2_0_epic',
            name='character_epic',
        ),
        migrations.DeleteModel(
            name='War_1_5_Epic',
        ),
        migrations.DeleteModel(
            name='War_1_5_Epic_PreQuest',
        ),
        migrations.DeleteModel(
            name='War_2_0_Epic',
        ),
    ]
